[tool.poetry]
name = "epoch8-smartrec-client"
version = "0.1.0-dev.1"
description = ""
authors = ["Shakirov Renat <renat@epoch8.co>"]
readme = "README.md"
packages = [
    { include = "smartrec_client", from = "." }
]


[tool.poetry.dependencies]
python = ">=3.10,<4"
setuptools = { version = ">=74.1.2"}
tritonclient = {extras = ["all"], version = ">=2.43.0,<=2.49.0"}

[tool.poetry.group.dev.dependencies]
pytest = "*"
flake8 = "*"
isort = "*"
black = "*"
mypy = "^1.14.0"


[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"