[tool.poetry]
name = "smartrec_client"
version = "0.1.0"
description = ""
authors = ["Shakirov Renat <renat@epoch8.co>"]
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.10,<4"
setuptools = { version = ">=74.1.2"}
tritonclient = {extras = ["all"], version = ">=2.43.0,<=2.49.0"}

[tool.poetry.group.dev.dependencies]
pytest = "*"
flake8 = "*"


[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"