[project]
name = "smartrec-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <4"
dependencies = ["tritonclient[all]>=2.43.0,<=2.49.0"]

authors = [{ name = "Shakirov Renat", email = "renat@epoch8.co" }]

[tool.uv]
dev-dependencies = ["pytest"]

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
