backend: "python"


parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "$$TRITON_MODEL_DIRECTORY/runtime_envs/runtime_env.tgz"}
}

input [
  {
    name: "user_ids"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  },
  {
    name: "item_ids"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  },
  {
    name: "items_to_recommend"
    data_type: TYPE_STRING
    dims: [ -1 ]
    optional: true
  },
  {
    name: "history"
    data_type: TYPE_STRING
    dims: [ -1 ]
    optional: true
  },
  {
    name: "top_n"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "filter_viewed"
    data_type: TYPE_BOOL
    dims: [ 1 ]
  }
]


output [
  {
    name: "item_ids"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "strategy"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

max_batch_size: 1

dynamic_batching {
  max_queue_delay_microseconds: 0
}

instance_group [{ kind: KIND_CPU, count: 1 }]